/**
 * GEPA Faza 1 — Gen 1 mutation #1 of claude.
 *
 * Generated by Opus 4.7 mutation oracle per Amendment 2 §4 forked template
 * (non-qwen branch). Cell-semantic boundaries preserved
 * via mutation-validator.ts SHA pins.
 *
 * Evidence: benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 retrieval-engagement signal + Amendment 2 §3 retrieval-engagement bonus; addresses Phase 4.3 T2 failure modes (unsupported-specifics, missed/shallow coverage, conflation/weak-synthesis)
 *
 * Baseline anchor: packages/agent/src/prompt-shapes/claude.ts (manifest v7
 * §gepa.mutation_validator.baseline_shape_shas[claude.ts]).
 */

import {
  type PromptShape,
  type SystemPromptInput,
  type SoloUserPromptInput,
  type MultiStepKickoffInput,
  type RetrievalInjectionInput,
  MULTI_STEP_ACTION_CONTRACT,
} from '../types.js';

export const claudeGen1V1Shape: PromptShape = {
  name: 'claude-gen1-v1',
  metadata: {
    description: 'Narrative system prompt with XML-style structure; for Claude Opus / Sonnet / Haiku.',
    modelClass: 'claude',
    evidence_link: "benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 retrieval-engagement signal + Amendment 2 §3 retrieval-engagement bonus; addresses Phase 4.3 T2 failure modes (unsupported-specifics, missed/shallow coverage, conflation/weak-synthesis)",
    defaultThinking: true,
    defaultMaxTokens: 4096,
  },

  systemPrompt(input: SystemPromptInput): string {
    const { persona, question, isMultiStep, maxSteps = 5, maxRetrievalsPerStep = 8 } = input;
    if (!isMultiStep) {
      return [
        '<role>',
        persona,
        '</role>',
        '',
        '<reasoning_protocol>',
        'Before composing your answer, internally work through these steps:',
        '  1. Decompose the question into its distinct sub-claims or sub-questions.',
        '  2. For each sub-claim, locate the SPECIFIC passages in the materials that support it.',
        '  3. Note which sub-claims are well-supported vs. partially-supported vs. unsupported.',
        '  4. Identify any DISTINCT risks/factors that should be separated rather than blended.',
        '  5. Flag any temptation to assert specifics not present in the materials — and resist it.',
        '</reasoning_protocol>',
        '',
        '<grounding_rules>',
        'Every specific claim (number, name, date, mechanism) MUST trace to the materials.',
        'If the materials are silent on a point, say so explicitly rather than inventing detail.',
        'When multiple risks or factors are present, enumerate them separately before synthesising.',
        '</grounding_rules>',
        '',
        'Answer the question precisely and substantively, grounded strictly in the materials provided.',
      ].join('\n');
    }
    return [
      '<role>',
      persona,
      '</role>',
      '',
      '<task>',
      'You have access to a private corpus of materials about this scenario via a retrieval tool.',
      'You CANNOT see the materials directly. You MUST request retrievals to get information.',
      'Insufficient retrieval is the dominant failure mode on this benchmark — err toward MORE targeted retrievals, not fewer.',
      '</task>',
      '',
      '<protocol>',
      MULTI_STEP_ACTION_CONTRACT,
      '',
      `You have a maximum of ${maxSteps} turns. Plan accordingly.`,
      `Each retrieval returns up to ${maxRetrievalsPerStep} most relevant document chunks.`,
      'A good retrieval query is 5-15 words and targets specific information.',
      '</protocol>',
      '',
      '<reasoning_protocol>',
      'On every turn, before emitting your action JSON, internally walk through:',
      '  1. Sub-question inventory: what distinct sub-questions does the question decompose into?',
      '  2. Coverage check: which sub-questions have I retrieved evidence for, and which remain unaddressed?',
      '  3. Gap identification: what specific facts, mechanisms, entities, or risks are still missing?',
      '  4. Next-action choice: if ANY sub-question lacks grounding, choose retrieve with a targeted query;',
      '     only choose finalize when every sub-question has supporting evidence in hand.',
      '  5. Anti-conflation: when multiple risks/factors appear, plan to keep them SEPARATE in the final answer.',
      '</reasoning_protocol>',
      '',
      '<grounding_rules>',
      'Do not assert specifics (numbers, names, dates, causal mechanisms) absent from retrieved chunks.',
      'If retrievals are silent on a sub-question, either retrieve again with a refined query or note the gap explicitly.',
      '</grounding_rules>',
      '',
      '<question>',
      question,
      '</question>',
    ].join('\n');
  },

  soloUserPrompt(input: SoloUserPromptInput): string {
    return [
      '<context>',
      input.persona,
      '</context>',
      '',
      '<materials>',
      input.materials,
      '</materials>',
      '',
      '<question>',
      input.question,
      '</question>',
      '',
      '<answer_plan>',
      'Step 1 — Decompose: list the distinct sub-questions implicit in the question above.',
      'Step 2 — Locate: for each sub-question, identify the supporting passages in <materials>.',
      'Step 3 — Separate: if multiple risks/factors/entities are involved, treat them as DISTINCT items.',
      'Step 4 — Audit: verify every specific claim you intend to make is grounded in <materials>; drop or hedge any that are not.',
      'Step 5 — Compose: produce a precise, substantive answer that covers every sub-question.',
      '</answer_plan>',
      '',
      'Answer the question above based strictly on the materials. Be specific, substantive, and grounded — no invented details.',
    ].join('\n');
  },

  multiStepKickoffUserPrompt(_input: MultiStepKickoffInput): string {
    return [
      'Begin.',
      'First, internally enumerate the sub-questions you will need to answer and the gaps you must fill via retrieval.',
      'Then output your first action JSON.',
    ].join('\n');
  },

  retrievalInjectionUserPrompt(input: RetrievalInjectionInput): string {
    return [
      `<retrieval_results query="${input.query}" count="${input.resultCount}">`,
      input.results,
      '</retrieval_results>',
      '',
      '<turn_review>',
      'Before deciding, check: which sub-questions are now covered by retrieved evidence, and which remain open?',
      'If any sub-question is still unsupported, prefer another targeted retrieve over finalize.',
      '</turn_review>',
      '',
      'Next action JSON?',
    ].join('\n');
  },
};
