/**
 * GEPA Faza 1 — Gen 1 mutation #2 of claude.
 *
 * Generated by Opus 4.7 mutation oracle per Amendment 2 §4 forked template
 * (non-qwen branch). Cell-semantic boundaries preserved
 * via mutation-validator.ts SHA pins.
 *
 * Evidence: benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 retrieval-engagement signal + Amendment 2 §3 retrieval-engagement bonus; addresses Phase 4.3 T2 modes (unsupported-specifics, missed-coverage, conflation/weak-synthesis)
 *
 * Baseline anchor: packages/agent/src/prompt-shapes/claude.ts (manifest v7
 * §gepa.mutation_validator.baseline_shape_shas[claude.ts]).
 */

import {
  type PromptShape,
  type SystemPromptInput,
  type SoloUserPromptInput,
  type MultiStepKickoffInput,
  type RetrievalInjectionInput,
  MULTI_STEP_ACTION_CONTRACT,
} from '../types.js';

export const claudeGen1V2Shape: PromptShape = {
  name: 'claude-gen1-v2',
  metadata: {
    description: 'Narrative system prompt with XML-style structure; for Claude Opus / Sonnet / Haiku.',
    modelClass: 'claude',
    evidence_link: "benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 retrieval-engagement signal + Amendment 2 §3 retrieval-engagement bonus; addresses Phase 4.3 T2 modes (unsupported-specifics, missed-coverage, conflation/weak-synthesis)",
    defaultThinking: true,
    defaultMaxTokens: 4096,
  },

  systemPrompt(input: SystemPromptInput): string {
    const { persona, question, isMultiStep, maxSteps = 5, maxRetrievalsPerStep = 8 } = input;
    if (!isMultiStep) {
      return [
  '<role>',
  persona,
  '</role>',
  '',
  '<reasoning_protocol>',
  'Before composing your answer, briefly work through these steps internally:',
  '  1. Identify what the question is actually asking (decompose into sub-questions if compound).',
  '  2. Inventory the materials: which passages bear on each sub-question?',
  '  3. Separate distinct items (risks, factors, entities) — do NOT blend them together.',
  '  4. Confirm every specific claim you make is anchored in the materials; if not anchored, drop it or mark as inference.',
  '</reasoning_protocol>',
  '',
  '<answer_constraints>',
  '  - Be specific and substantive, but ground every specific in the materials.',
  '  - Do not introduce facts, numbers, names, or details that are not present in the materials.',
  '  - If the materials are silent or ambiguous on a point, say so explicitly rather than filling the gap.',
  '  - Cover the full scope of what the materials say on the question; do not stop at the first plausible answer.',
  '</answer_constraints>',
  '',
  'Answer the question precisely and substantively, grounded strictly in the materials provided.',
].join('\n');
    }
    return [
  '<role>',
  persona,
  '</role>',
  '',
  '<task>',
  'You have access to a private corpus of materials about this scenario via a retrieval tool.',
  'You CANNOT see the materials directly. You MUST request retrievals to gather evidence before finalizing.',
  'Answers given without first retrieving sufficient evidence will be unsupported and will fail.',
  '</task>',
  '',
  '<protocol>',
  MULTI_STEP_ACTION_CONTRACT,
  '',
  `You have a maximum of ${maxSteps} turns. Plan accordingly.`,
  `Each retrieval returns up to ${maxRetrievalsPerStep} most relevant document chunks.`,
  'A good retrieval query is 5-15 words and targets specific information.',
  '</protocol>',
  '',
  '<retrieval_engagement>',
  '  Strong performance on this benchmark correlates with active corpus engagement.',
  '  Expectation: issue multiple retrievals (typically 2-4 across distinct sub-topics) before finalizing,',
  '  unless one retrieval demonstrably covers the full question. A single retrieval is rarely sufficient',
  '  for compound questions. Vary your queries to probe different facets rather than rephrasing the same query.',
  '</retrieval_engagement>',
  '',
  '<reasoning_scaffold>',
  '  Before each action, think through (internally):',
  '    a. What sub-questions does the prompt contain? (decompose)',
  '    b. Which sub-questions do I already have evidence for, and which are still open?',
  '    c. If open sub-questions remain, my next action should be `retrieve` with a query targeting the gap.',
  '    d. Only choose `finalize` when every sub-question has supporting evidence from retrievals.',
  '  When you finalize: separate distinct items rather than conflating them, ground every specific in retrieved text,',
  '  and do not invent details beyond what retrievals returned.',
  '</reasoning_scaffold>',
  '',
  '<question>',
  question,
  '</question>',
].join('\n');
  },

  soloUserPrompt(input: SoloUserPromptInput): string {
    return [
  '<context>',
  input.persona,
  '</context>',
  '',
  '<materials>',
  input.materials,
  '</materials>',
  '',
  '<question>',
  input.question,
  '</question>',
  '',
  '<instructions>',
  'Work through this in stages:',
  '  Stage 1 — Decompose the question into its component sub-questions.',
  '  Stage 2 — For each sub-question, locate the relevant evidence in <materials> and note what it says.',
  '  Stage 3 — Distinguish separate items; do not blend distinct risks, factors, or entities together.',
  '  Stage 4 — Compose the answer: specific, substantive, and anchored to <materials>.',
  'Hard constraints: do NOT add specifics absent from the materials. If the materials do not address a point,',
  'state that explicitly rather than speculating. Cover the full scope the materials support.',
  '</instructions>',
].join('\n');
  },

  multiStepKickoffUserPrompt(_input: MultiStepKickoffInput): string {
    return 'Begin. First, internally decompose the question into sub-questions and identify which gap your initial retrieval will target. Then output your first action JSON now.';
  },

  retrievalInjectionUserPrompt(input: RetrievalInjectionInput): string {
    return [
  `<retrieval_results query="${input.query}" count="${input.resultCount}">`,
  input.results,
  '</retrieval_results>',
  '',
  '<assess>',
  '  Briefly consider (internally): which sub-questions did this retrieval answer, and which remain open?',
  '  If gaps remain, your next action should be another `retrieve` with a query targeting an unaddressed facet.',
  '  Only `finalize` when every sub-question has supporting evidence.',
  '</assess>',
  '',
  'Next action JSON?',
].join('\n');
  },
};
