/**
 * GEPA Faza 1 — Gen 1 mutation #1 of generic-simple.
 *
 * Generated by Opus 4.7 mutation oracle per Amendment 2 §4 forked template
 * (non-qwen branch). Cell-semantic boundaries preserved
 * via mutation-validator.ts SHA pins.
 *
 * Evidence: benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 + Amendment 2 §3 retrieval-engagement bonus
 *
 * Baseline anchor: packages/agent/src/prompt-shapes/generic-simple.ts (manifest v7
 * §gepa.mutation_validator.baseline_shape_shas[generic-simple.ts]).
 */

import {
  type PromptShape,
  type SystemPromptInput,
  type SoloUserPromptInput,
  type MultiStepKickoffInput,
  type RetrievalInjectionInput,
  MULTI_STEP_ACTION_CONTRACT,
} from '../types.js';

export const genericSimpleGen1V1Shape: PromptShape = {
  name: 'generic-simple-gen1-v1',
  metadata: {
    description: 'Portable fallback shape — plain markdown, no model-specific framing. Used when alias is not in the registry.',
    modelClass: 'generic',
    evidence_link: "benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 + Amendment 2 §3 retrieval-engagement bonus",
    defaultThinking: false,
    defaultMaxTokens: 4096,
  },

  systemPrompt(input: SystemPromptInput): string {
    const { persona, question, isMultiStep, maxSteps = 5, maxRetrievalsPerStep = 8 } = input;
    if (!isMultiStep) {
      return [
  persona,
  '',
  'Before answering, take a moment to plan your response:',
  '  1. Identify what the question is actually asking.',
  '  2. Scan the materials for every passage that bears on it.',
  '  3. Separate distinct points or risks rather than blending them.',
  '  4. Stay strictly within what the materials support — do not invent specifics.',
  '',
  'Then write a specific, substantive answer grounded only in the materials provided.',
].join('\n');
    }
    return [
  persona,
  '',
  'You have access to a private corpus via a retrieval tool. You are expected to USE it actively — most tasks require multiple retrievals to cover the source material adequately. Shallow single-shot answers tend to miss important content.',
  '',
  'Reasoning scaffold for each turn:',
  '  1. Restate what you still need to learn before you can answer well.',
  '  2. Decide whether another retrieval (with a fresh, targeted query) would surface material you have not yet seen.',
  '  3. Only choose finalize when further retrieval is unlikely to add coverage.',
  '  4. When finalizing, separate distinct points rather than conflating them, and ground every specific claim in retrieved text.',
  '',
  MULTI_STEP_ACTION_CONTRACT,
  '',
  `You have up to ${maxSteps} turns. Each retrieval returns up to ${maxRetrievalsPerStep} chunks. Prefer issuing several varied retrievals over finalizing early.`,
  '',
  `Question: ${question}`,
].join('\n');
  },

  soloUserPrompt(input: SoloUserPromptInput): string {
    return [
  input.persona,
  '',
  'Materials:',
  '',
  input.materials,
  '',
  `Question: ${input.question}`,
  '',
  'Plan briefly: which parts of the materials are relevant, and what distinct points need to be made? Then answer specifically, keeping each point separate and staying strictly within what the materials support.',
].join('\n');
  },

  multiStepKickoffUserPrompt(_input: MultiStepKickoffInput): string {
    return 'Begin. Think about what the question requires, then output your first action JSON. If you need information from the corpus to answer well, your first action should be a retrieval with a focused query.';
  },

  retrievalInjectionUserPrompt(input: RetrievalInjectionInput): string {
    return [
  `Retrieval results for "${input.query}" (${input.resultCount} hits):`,
  '',
  input.results,
  '',
  'Consider: do these results cover the question fully, or are there angles still unexamined? Output your next action JSON.',
].join('\n');
  },
};
