/**
 * GEPA Faza 1 — Gen 1 mutation #2 of generic-simple.
 *
 * Generated by Opus 4.7 mutation oracle per Amendment 2 §4 forked template
 * (non-qwen branch). Cell-semantic boundaries preserved
 * via mutation-validator.ts SHA pins.
 *
 * Evidence: benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 + Amendment 2 §3 retrieval-engagement bonus
 *
 * Baseline anchor: packages/agent/src/prompt-shapes/generic-simple.ts (manifest v7
 * §gepa.mutation_validator.baseline_shape_shas[generic-simple.ts]).
 */

import {
  type PromptShape,
  type SystemPromptInput,
  type SoloUserPromptInput,
  type MultiStepKickoffInput,
  type RetrievalInjectionInput,
  MULTI_STEP_ACTION_CONTRACT,
} from '../types.js';

export const genericSimpleGen1V2Shape: PromptShape = {
  name: 'generic-simple-gen1-v2',
  metadata: {
    description: 'Portable fallback shape — plain markdown, no model-specific framing. Used when alias is not in the registry.',
    modelClass: 'generic',
    evidence_link: "benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 + Amendment 2 §3 retrieval-engagement bonus",
    defaultThinking: false,
    defaultMaxTokens: 4096,
  },

  systemPrompt(input: SystemPromptInput): string {
    const { persona, question, isMultiStep, maxSteps = 5, maxRetrievalsPerStep = 8 } = input;
    if (!isMultiStep) {
      return [persona, '', 'Task: answer the question grounded strictly in the provided materials.', '', 'Before answering, internally work through these steps:', '1. Identify every distinct sub-question or claim the prompt requires.', '2. Scan the materials and note which passages support each sub-question; flag any that are unsupported.', '3. Separate distinct risks, entities, or factors — do not blend them into a single synthesis.', '4. Drop any specific (number, name, date, mechanism) that is not directly attested in the materials.', '', 'Then write the answer. Be specific and substantive, but every specific must trace to the materials. If a sub-question is not covered by the materials, say so explicitly rather than guessing.'].join('\n');
    }
    return [persona, '', 'You have access to a private corpus via a retrieval tool. You are expected to actively retrieve — a single retrieval is rarely sufficient for multi-faceted questions. Plan to issue multiple, varied queries that cover distinct sub-topics, entities, and risks.', '', 'Reasoning loop for each turn:', '1. Decompose the question into its sub-parts (entities, risks, mechanisms, time periods).', '2. Inventory what you already have from prior retrievals; identify the largest remaining gap.', '3. Issue a retrieval whose query targets that gap with specific terminology — avoid repeating prior queries.', '4. Only finalize when every sub-part has direct corpus support, or when remaining turns force a stop.', '', 'When you finalize: keep distinct risks/entities separate, do not invent specifics beyond retrieved chunks, and explicitly note any sub-part that retrieval did not cover.', '', MULTI_STEP_ACTION_CONTRACT, '', `Budget: up to ${maxSteps} turns; each retrieval returns up to ${maxRetrievalsPerStep} chunks. Use the budget — under-retrieval is a known failure mode.`, '', `Question: ${question}`].join('\n');
  },

  soloUserPrompt(input: SoloUserPromptInput): string {
    return [input.persona, '', 'Materials:', '', input.materials, '', `Question: ${input.question}`, '', 'Procedure:', '- List the sub-questions implied by the question.', '- For each, cite the supporting passage from the materials (or mark as uncovered).', '- Keep distinct factors/risks/entities separated; do not conflate.', '- Omit any specific not grounded in the materials.', '', 'Now produce the final answer following that procedure.'].join('\n');
  },

  multiStepKickoffUserPrompt(_input: MultiStepKickoffInput): string {
    return ['Begin.', '', 'First, briefly decompose the question into its sub-parts (entities, risks, mechanisms). Then output your first action JSON — typically a retrieval targeting the highest-priority sub-part with specific query terms.'].join('\n');
  },

  retrievalInjectionUserPrompt(input: RetrievalInjectionInput): string {
    return [`Retrieval results for "${input.query}" (${input.resultCount} hits):`, '', input.results, '', 'Update your working notes:', '- Which sub-parts of the question are now supported by retrieved evidence?', '- Which sub-parts remain uncovered or thinly covered?', '- Is there a distinct angle (different entity, risk, time period, mechanism) not yet queried?', '', 'If gaps remain and turns are available, retrieve again with a query that targets a new gap (do not repeat prior queries). Otherwise, finalize. Output your next action JSON.'].join('\n');
  },
};
