/**
 * GEPA Faza 1 — Gen 1 mutation #1 of gpt.
 *
 * Generated by Opus 4.7 mutation oracle per Amendment 2 §4 forked template
 * (non-qwen branch). Cell-semantic boundaries preserved
 * via mutation-validator.ts SHA pins.
 *
 * Evidence: GEPA Gen 1 mutation #1: benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 retrieval-engagement signal + Amendment 2 §3; addresses Phase 4.3 T2 categories (unsupported-specifics, shallow coverage, weak-synthesis)
 *
 * Baseline anchor: packages/agent/src/prompt-shapes/gpt.ts (manifest v7
 * §gepa.mutation_validator.baseline_shape_shas[gpt.ts]).
 */

import {
  type PromptShape,
  type SystemPromptInput,
  type SoloUserPromptInput,
  type MultiStepKickoffInput,
  type RetrievalInjectionInput,
  MULTI_STEP_ACTION_CONTRACT,
} from '../types.js';

export const gptGen1V1Shape: PromptShape = {
  name: 'gpt-gen1-v1',
  metadata: {
    description: 'Terse direct framing for GPT-5.4 and other reasoning-heavy GPT models; minimal decoration.',
    modelClass: 'gpt',
    evidence_link: "GEPA Gen 1 mutation #1: benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 retrieval-engagement signal + Amendment 2 §3; addresses Phase 4.3 T2 categories (unsupported-specifics, shallow coverage, weak-synthesis)",
    defaultThinking: false,
    defaultMaxTokens: 4096,
  },

  systemPrompt(input: SystemPromptInput): string {
    const { persona, question, isMultiStep, maxSteps = 5, maxRetrievalsPerStep = 8 } = input;
    if (!isMultiStep) {
      return [
        persona,
        'Before answering: (1) scan the materials, (2) list the distinct points relevant to the question, (3) separate them rather than blending. Cite only what the materials state. If unsupported, say so.',
      ].join('\n\n');
    }
    return [
      persona,
      'You answer by issuing retrieval queries against a private corpus you cannot see directly. Plan before each action: what gap remains, what query closes it, when you have enough to finalize.',
      MULTI_STEP_ACTION_CONTRACT,
      `Budget: up to ${maxSteps} turns; up to ${maxRetrievalsPerStep} chunks per retrieval. Prefer multiple targeted retrievals over one broad query — coverage matters more than speed.`,
      'Ground every claim in retrieved text. Do not invent specifics. Keep distinct risks/points separate in your final answer.',
      `Question: ${question}`,
    ].join('\n\n');
  },

  soloUserPrompt(input: SoloUserPromptInput): string {
    return [
      input.persona,
      `Materials:\n${input.materials}`,
      `Question: ${input.question}`,
      'Steps: (1) enumerate the distinct points the materials make about this question, (2) keep them separate, (3) answer concretely citing only material-supported specifics. Flag anything the materials do not cover rather than filling gaps.',
    ].join('\n\n');
  },

  multiStepKickoffUserPrompt(_input: MultiStepKickoffInput): string {
    return [
      'Plan briefly: what is the first information gap, and what query targets it? Then output your first JSON action.',
    ].join('\n');
  },

  retrievalInjectionUserPrompt(input: RetrievalInjectionInput): string {
    return [
      `Retrieval ("${input.query}", ${input.resultCount} hits):`,
      input.results,
      'Assess: what did this confirm, what gap remains, is another retrieval warranted before finalize? Next JSON action:',
    ].join('\n\n');
  },
};
