/**
 * GEPA Faza 1 — Gen 1 mutation #2 of gpt.
 *
 * Generated by Opus 4.7 mutation oracle per Amendment 2 §4 forked template
 * (non-qwen branch). Cell-semantic boundaries preserved
 * via mutation-validator.ts SHA pins.
 *
 * Evidence: benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 + Amendment 2 §3 retrieval-engagement bonus (gpt mutation #2: explicit decomposition + coverage scaffolding to address unsupported-specifics and shallow-coverage T2 modes)
 *
 * Baseline anchor: packages/agent/src/prompt-shapes/gpt.ts (manifest v7
 * §gepa.mutation_validator.baseline_shape_shas[gpt.ts]).
 */

import {
  type PromptShape,
  type SystemPromptInput,
  type SoloUserPromptInput,
  type MultiStepKickoffInput,
  type RetrievalInjectionInput,
  MULTI_STEP_ACTION_CONTRACT,
} from '../types.js';

export const gptGen1V2Shape: PromptShape = {
  name: 'gpt-gen1-v2',
  metadata: {
    description: 'Terse direct framing for GPT-5.4 and other reasoning-heavy GPT models; minimal decoration.',
    modelClass: 'gpt',
    evidence_link: "benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 + Amendment 2 §3 retrieval-engagement bonus (gpt mutation #2: explicit decomposition + coverage scaffolding to address unsupported-specifics and shallow-coverage T2 modes)",
    defaultThinking: false,
    defaultMaxTokens: 4096,
  },

  systemPrompt(input: SystemPromptInput): string {
    const { persona, question, isMultiStep, maxSteps = 5, maxRetrievalsPerStep = 8 } = input;
    if (!isMultiStep) {
      return [persona, 'Procedure: (1) enumerate every distinct claim, risk, or entity present in the materials before drafting; (2) group related items, separating distinct risks rather than blending them; (3) answer using only what the materials state — no outside specifics, numbers, or named entities the materials do not contain; (4) if materials are silent on a sub-question, say so explicitly.'].join('\n\n');
    }
    return [persona, 'You answer by issuing retrieval queries against a private corpus you cannot read directly. Default to retrieving: each finalize without prior retrieval risks unsupported specifics.', MULTI_STEP_ACTION_CONTRACT, 'Per-turn reasoning protocol (think internally, emit only the JSON action):', '  • What sub-question or facet is still uncovered?', '  • Which distinct angle has retrieval not yet probed (entities, mechanisms, counter-evidence, edge cases)?', '  • Compose a query targeting that gap; avoid repeating prior phrasings.', '  • Finalize only when every facet of the question has at least one retrieval grounding it and remaining gaps are explicitly acknowledged.', `Budget: up to ${maxSteps} turns, ${maxRetrievalsPerStep} chunks per retrieval. Prefer multiple targeted retrievals over one broad one.`, `Question: ${question}`].join('\n\n');
  },

  soloUserPrompt(input: SoloUserPromptInput): string {
    return [input.persona, `Materials:\n${input.materials}`, `Question: ${input.question}`, 'Before answering, internally list the distinct facets the question asks about and the specific passages in the materials that address each. Then answer concretely, separating distinct risks/claims rather than conflating them, and grounding every specific (numbers, names, mechanisms) in the materials. If the materials do not address a facet, state that explicitly instead of inferring.'].join('\n\n');
  },

  multiStepKickoffUserPrompt(_input: MultiStepKickoffInput): string {
    return 'Begin. Identify the facets of the question, pick the most under-covered one, and emit your first JSON action (prefer retrieve unless the question is fully answerable from prior context):';
  },

  retrievalInjectionUserPrompt(input: RetrievalInjectionInput): string {
    return [`Retrieval ("${input.query}", ${input.resultCount} hits):`, input.results, 'Assess: which facets are now covered, which remain open, and whether any specific you might cite is actually grounded in retrieved text. Then emit the next JSON action — retrieve again if gaps remain, finalize only when coverage is sufficient:'].join('\n\n');
  },
};
