/**
 * GEPA Faza 1 — Gen 1 mutation #1 of qwen-thinking.
 *
 * Generated by Opus 4.7 mutation oracle per Amendment 2 §4 forked template
 * (qwen branch). Cell-semantic boundaries preserved
 * via mutation-validator.ts SHA pins.
 *
 * Evidence: benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log (Gen 1 mutation oracle); Phase 4.5 retrieval-engagement signal (Qwen 1.33×/task vs Opus 2.33×/task on byte-identical tool surface); Amendment 2 §3 retrieval-engagement bonus (target ≥1.5 retrievals/task to escape penalty zone, ≥2.0 for Opus parity proxy); decisions/2026-04-28-phase-4-3-rescore-delta-report.md (T2 failure modes: unsupported-specifics 10/26, missed/shallow 9/26, conflation 5/26)
 *
 * Baseline anchor: packages/agent/src/prompt-shapes/qwen-thinking.ts (manifest v7
 * §gepa.mutation_validator.baseline_shape_shas[qwen-thinking.ts]).
 */

import {
  type PromptShape,
  type SystemPromptInput,
  type SoloUserPromptInput,
  type MultiStepKickoffInput,
  type RetrievalInjectionInput,
  MULTI_STEP_ACTION_CONTRACT,
} from '../types.js';

export const qwenThinkingGen1V1Shape: PromptShape = {
  name: 'qwen-thinking-gen1-v1',
  metadata: {
    description: 'Minimal scaffolding for Qwen thinking-on; the model handles reasoning structure internally.',
    modelClass: 'qwen-thinking',
    evidence_link: "benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log (Gen 1 mutation oracle); Phase 4.5 retrieval-engagement signal (Qwen 1.33×/task vs Opus 2.33×/task on byte-identical tool surface); Amendment 2 §3 retrieval-engagement bonus (target ≥1.5 retrievals/task to escape penalty zone, ≥2.0 for Opus parity proxy); decisions/2026-04-28-phase-4-3-rescore-delta-report.md (T2 failure modes: unsupported-specifics 10/26, missed/shallow 9/26, conflation 5/26)",
    defaultThinking: true,
    defaultMaxTokens: 16000,
  },

  systemPrompt(input: SystemPromptInput): string {
    const { persona, question, isMultiStep, maxSteps = 5, maxRetrievalsPerStep = 8 } = input;
    if (!isMultiStep) {
      return [
        persona,
        '',
        'Answer the question precisely and substantively, grounded strictly in the materials provided.',
        '',
        'Before finalizing, check: (a) is every specific claim traceable to the materials? (b) which parts of the question remain only partially covered? (c) are distinct items kept separate rather than blended? Revise if any check fails.',
      ].join('\n');
    }
    return [
      persona,
      '',
      '## Task',
      'You have access to a private corpus via a retrieval tool. You cannot see materials directly — request retrievals to get information.',
      '',
      '## Protocol',
      MULTI_STEP_ACTION_CONTRACT,
      '',
      `Max ${maxSteps} turns. Each retrieval returns up to ${maxRetrievalsPerStep} chunks.`,
      '',
      '## Retrieval discipline',
      '- A single retrieval is rarely sufficient. Continue retrieving until you have evidence from at least 2 distinct queries before finalizing.',
      '- After each retrieval, refine your next query based on what the prior results revealed or omitted — vary terms, angles, or entities rather than repeating.',
      '- Before emitting a finalize action, ask explicitly: what gap in evidence remains? Which sub-parts of the question are still under-supported? If any gap exists, issue another retrieval instead of finalizing.',
      '- Ground every specific (names, numbers, dates, claims) in retrieved chunks. If a specific is not in the evidence, omit it rather than infer it.',
      '- Keep distinct items, risks, or entities separated in your synthesis; do not blend them.',
      '',
      '## Question',
      question,
    ].join('\n');
  },

  soloUserPrompt(input: SoloUserPromptInput): string {
    return [
      input.persona,
      '',
      '## Materials',
      '',
      input.materials,
      '',
      '## Question',
      '',
      input.question,
      '',
      'Answer the question above based strictly on the materials. Be specific and substantive. Keep distinct items separated; do not introduce specifics absent from the materials.',
    ].join('\n');
  },

  multiStepKickoffUserPrompt(_input: MultiStepKickoffInput): string {
    return [
      'Begin. Plan to issue at least 2 distinct retrieval queries before finalizing — a single retrieval will almost certainly leave gaps.',
      'Output your first action JSON now.',
    ].join('\n');
  },

  retrievalInjectionUserPrompt(input: RetrievalInjectionInput): string {
    return [
      `## Retrieval results for "${input.query}" (${input.resultCount} hits)`,
      '',
      input.results,
      '',
      'Before deciding: what aspect of the question is still uncovered or weakly supported by the evidence so far? If any gap remains, issue another retrieval with a refined query (different terms or angle). Only finalize when no material gap is left.',
      '',
      'Next action JSON?',
    ].join('\n');
  },
};
