/**
 * GEPA Faza 1 — Gen 1 mutation #2 of qwen-thinking.
 *
 * Generated by Opus 4.7 mutation oracle per Amendment 2 §4 forked template
 * (qwen branch). Cell-semantic boundaries preserved
 * via mutation-validator.ts SHA pins.
 *
 * Evidence: benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log (Gen 1 mutation oracle); Phase 4.5 retrieval-engagement signal (Qwen 1.33×/task vs Opus 2.33×/task); Amendment 2 §3 retrieval-engagement bonus — variant #2 targets multi-turn retrieval discipline + gap-driven query refinement to escape penalty zone (mean retrievals ≥ 1.5, ideal ≥ 2.0)
 *
 * Baseline anchor: packages/agent/src/prompt-shapes/qwen-thinking.ts (manifest v7
 * §gepa.mutation_validator.baseline_shape_shas[qwen-thinking.ts]).
 */

import {
  type PromptShape,
  type SystemPromptInput,
  type SoloUserPromptInput,
  type MultiStepKickoffInput,
  type RetrievalInjectionInput,
  MULTI_STEP_ACTION_CONTRACT,
} from '../types.js';

export const qwenThinkingGen1V2Shape: PromptShape = {
  name: 'qwen-thinking-gen1-v2',
  metadata: {
    description: 'Minimal scaffolding for Qwen thinking-on; the model handles reasoning structure internally.',
    modelClass: 'qwen-thinking',
    evidence_link: "benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log (Gen 1 mutation oracle); Phase 4.5 retrieval-engagement signal (Qwen 1.33×/task vs Opus 2.33×/task); Amendment 2 §3 retrieval-engagement bonus — variant #2 targets multi-turn retrieval discipline + gap-driven query refinement to escape penalty zone (mean retrievals ≥ 1.5, ideal ≥ 2.0)",
    defaultThinking: true,
    defaultMaxTokens: 16000,
  },

  systemPrompt(input: SystemPromptInput): string {
    const { persona, question, isMultiStep, maxSteps = 5, maxRetrievalsPerStep = 8 } = input;
    if (!isMultiStep) {
      return [persona, '', 'Answer the question precisely and substantively, grounded strictly in the materials provided. Separate distinct risks/claims rather than blending them, and do not introduce specifics that the materials do not support.'].join('\n');
    }
    return [persona, '', '## Task', 'You have access to a private corpus via a retrieval tool. You cannot see materials directly — request retrievals to get information. Treat each retrieval as one slice of evidence: a single query rarely covers the question.', '', '## Protocol', MULTI_STEP_ACTION_CONTRACT, '', `Max ${maxSteps} turns. Each retrieval returns up to ${maxRetrievalsPerStep} chunks.`, '', '## Retrieval discipline', '- Plan to issue at least 2 distinct retrieval queries before finalizing; aim for 2–3 when the question has multiple facets (entities, risks, timeframes, comparisons).', '- After each retrieval, explicitly note (in your reasoning): which sub-parts of the question are now evidenced, and which remain uncovered or thinly supported.', '- Refine the next query based on the gap — vary phrasing, entities, or angle rather than repeating the prior query.', '- Before emitting a finalize action, ask yourself: "What gap in evidence remains? Is any specific I am about to assert ungrounded? Are distinct risks being conflated?" If any gap exists and turns remain, issue another retrieve action instead of finalizing.', '- Only finalize when coverage is adequate across the question and every specific in your answer traces to retrieved chunks.', '', '## Question', question].join('\n');
  },

  soloUserPrompt(input: SoloUserPromptInput): string {
    return [input.persona, '', '## Materials', '', input.materials, '', '## Question', '', input.question, '', 'Answer the question above based strictly on the materials. Be specific and substantive, but do not assert specifics the materials do not support. Keep distinct risks or claims separated rather than blended.'].join('\n');
  },

  multiStepKickoffUserPrompt(_input: MultiStepKickoffInput): string {
    return 'Begin. Plan to retrieve from at least 2 distinct angles before finalizing. Output your first action JSON now — typically a retrieve targeting the most central facet of the question.';
  },

  retrievalInjectionUserPrompt(input: RetrievalInjectionInput): string {
    return [`## Retrieval results for "${input.query}" (${input.resultCount} hits)`, '', input.results, '', 'Briefly assess: which parts of the question are now covered, and which gaps remain? If a gap exists and turns remain, issue another retrieve with a refined or differently-angled query rather than finalizing. Next action JSON?'].join('\n');
  },
};
