/**
 * GEPA Faza 1 — Gen 1 mutation #2 of qwen-non-thinking.
 *
 * Generated by Opus 4.7 mutation oracle per Amendment 2 §4 forked template
 * (qwen branch). Cell-semantic boundaries preserved
 * via mutation-validator.ts SHA pins.
 *
 * Evidence: benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 retrieval-engagement audit + Amendment 2 §3 retrieval-engagement bonus; baseline parse-rate evidence retained from commit b7e19c5 (Stage 3 v6 self-judge re-eval, 2000 calls thinking=off, 100% parse rate)
 *
 * Baseline anchor: packages/agent/src/prompt-shapes/qwen-non-thinking.ts (manifest v7
 * §gepa.mutation_validator.baseline_shape_shas[qwen-non-thinking.ts]).
 */

import {
  type PromptShape,
  type SystemPromptInput,
  type SoloUserPromptInput,
  type MultiStepKickoffInput,
  type RetrievalInjectionInput,
  MULTI_STEP_ACTION_CONTRACT,
} from '../types.js';

export const qwenNonThinkingGen1V2Shape: PromptShape = {
  name: 'qwen-non-thinking-gen1-v2',
  metadata: {
    description: 'Explicit structured-output template for Qwen thinking-off; for short binary/structured outputs (judge calls, classifiers).',
    modelClass: 'qwen-non-thinking',
    evidence_link: "benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 retrieval-engagement audit + Amendment 2 §3 retrieval-engagement bonus; baseline parse-rate evidence retained from commit b7e19c5 (Stage 3 v6 self-judge re-eval, 2000 calls thinking=off, 100% parse rate)",
    defaultThinking: false,
    defaultMaxTokens: 3000,
  },

  systemPrompt(input: SystemPromptInput): string {
    const { persona, question, isMultiStep, maxSteps = 5, maxRetrievalsPerStep = 8 } = input;
    if (!isMultiStep) {
      return [
        persona,
        '',
        'Answer the question precisely using ONLY the provided materials. Be concrete and specific; do not introduce facts, names, numbers, or claims not present in the materials.',
        'Before finalizing, scan the materials once more for any distinct point you may have skipped — separate distinct risks/items rather than blending them.',
        'Output only the answer — no preamble, no meta-commentary.',
      ].join('\n');
    }
    return [
      persona,
      '',
      'TASK: Answer the question using a retrieval tool. You cannot see materials directly — every fact in your final answer must trace to retrieved chunks.',
      '',
      'PROTOCOL (output exactly one JSON object per turn, no prose):',
      MULTI_STEP_ACTION_CONTRACT,
      '',
      'RETRIEVAL DISCIPLINE (critical — do not skip):',
      '- Do NOT finalize after a single retrieval. Issue at least 2 distinct retrieval queries (different angle, different keywords, or follow-up on a specific entity surfaced in the first batch) before considering finalize.',
      '- After each retrieval, ask yourself: (a) which sub-parts of the question are still unevidenced? (b) which entities/terms newly surfaced deserve a follow-up query? (c) did I conflate two distinct items that should be separated? If any answer is non-empty, issue another retrieve action.',
      '- Refine queries iteratively: do not repeat the same query verbatim; rephrase using terms discovered in prior results.',
      '- Only finalize when no evidence gap remains AND your answer cites only material grounded in retrieved chunks.',
      '',
      `RULES:`,
      `- Maximum ${maxSteps} turns; aim to use at least 2 retrieval turns before finalize.`,
      `- Each retrieval returns up to ${maxRetrievalsPerStep} chunks.`,
      `- Output JSON only — no markdown fences, no explanation.`,
      '',
      'QUESTION:',
      question,
    ].join('\n');
  },

  soloUserPrompt(input: SoloUserPromptInput): string {
    return [
      input.persona,
      '',
      'MATERIALS:',
      input.materials,
      '',
      'QUESTION:',
      input.question,
      '',
      'Answer based strictly on the materials above. Cover each distinct point the question asks about; keep separable items separate (do not merge them). Do not add specifics that are not in the materials. No preamble.',
    ].join('\n');
  },

  multiStepKickoffUserPrompt(_input: MultiStepKickoffInput): string {
    return [
      'Begin. Plan to issue at least 2 distinct retrieval queries before finalize — your first query should be broad enough to map the territory, with follow-up queries targeting specific entities or sub-questions surfaced in the first results.',
      'Output your first action JSON now (retrieve).',
    ].join('\n');
  },

  retrievalInjectionUserPrompt(input: RetrievalInjectionInput): string {
    return [
      `RETRIEVAL RESULTS (query: "${input.query}", ${input.resultCount} hits):`,
      input.results,
      '',
      'Gap-check before next action: (1) which sub-parts of the question remain unevidenced? (2) which entities/terms in these results deserve a targeted follow-up query? (3) are any items at risk of being conflated? If any gap exists, issue another retrieve with a refined query (do not repeat the prior query verbatim). Only finalize if no gap remains and you have evidence from at least 2 distinct queries.',
      '',
      'Next JSON action:',
    ].join('\n');
  },
};
