/**
 * GEPA Faza 1 — Gen 1 mutation #1 of qwen-non-thinking.
 *
 * Generated by Opus 4.7 mutation oracle per Amendment 2 §4 forked template
 * (qwen branch). Cell-semantic boundaries preserved
 * via mutation-validator.ts SHA pins.
 *
 * Evidence: benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 retrieval-engagement signal (Qwen 1.33×/task vs Opus 2.33×/task) + Amendment 2 §3 retrieval-engagement bonus; targets mean retrieval_calls/task >= 1.5 (escape penalty zone) toward 2.0 (Opus parity proxy)
 *
 * Baseline anchor: packages/agent/src/prompt-shapes/qwen-non-thinking.ts (manifest v7
 * §gepa.mutation_validator.baseline_shape_shas[qwen-non-thinking.ts]).
 */

import {
  type PromptShape,
  type SystemPromptInput,
  type SoloUserPromptInput,
  type MultiStepKickoffInput,
  type RetrievalInjectionInput,
  MULTI_STEP_ACTION_CONTRACT,
} from '../types.js';

export const qwenNonThinkingGen1V1Shape: PromptShape = {
  name: 'qwen-non-thinking-gen1-v1',
  metadata: {
    description: 'Explicit structured-output template for Qwen thinking-off; for short binary/structured outputs (judge calls, classifiers).',
    modelClass: 'qwen-non-thinking',
    evidence_link: "benchmarks/results/gepa-faza1/gen-1/mutation-oracle-run.log + Phase 4.5 retrieval-engagement signal (Qwen 1.33×/task vs Opus 2.33×/task) + Amendment 2 §3 retrieval-engagement bonus; targets mean retrieval_calls/task >= 1.5 (escape penalty zone) toward 2.0 (Opus parity proxy)",
    defaultThinking: false,
    defaultMaxTokens: 3000,
  },

  systemPrompt(input: SystemPromptInput): string {
    const { persona, question, isMultiStep, maxSteps = 5, maxRetrievalsPerStep = 8 } = input;
    if (!isMultiStep) {
      return [persona, '', 'Answer the question precisely. Ground every specific (numbers, names, dates, claims) in the materials provided. If a detail is not in the materials, omit it rather than guess. Be brief and concrete. Output only the answer — no preamble.'].join('\n');
    }
    return [persona, '', 'TASK: Answer the question using a retrieval tool. You cannot see materials directly — every specific in your final answer MUST come from retrieved chunks.', '', 'PROTOCOL (output exactly one JSON object per turn, no prose):', MULTI_STEP_ACTION_CONTRACT, '', 'RETRIEVAL DISCIPLINE (critical — single-shot retrieval is insufficient):', '- Issue at least 2 distinct retrieval queries before finalizing. One query rarely covers a real question.', '- After each retrieval, ask yourself: (a) what sub-aspect of the question is still uncovered? (b) what entity, mechanism, or counter-angle did the first query miss? (c) is any specific I would write unsupported by retrieved text? If any answer is yes, issue another retrieval.', '- Refine each follow-up query — do not repeat prior wording. Vary entities, synonyms, or angles (e.g. risks vs mitigations, mechanism vs evidence, primary vs secondary sources).', '- Separate distinct risks/factors/items rather than blending them. If the question implies multiple facets, retrieve for each facet.', '- Only emit {"action":"finalize",...} when no evidence gap remains AND you have results from >= 2 distinct queries.', '', `RULES:`, `- Maximum ${maxSteps} turns — budget them for iterative retrieval, not a single shot.`, `- Each retrieval returns up to ${maxRetrievalsPerStep} chunks.`, '- Output JSON only — no markdown fences, no explanation.', '', 'QUESTION:', question].join('\n');
  },

  soloUserPrompt(input: SoloUserPromptInput): string {
    return [input.persona, '', 'MATERIALS:', input.materials, '', 'QUESTION:', input.question, '', 'Answer based strictly on the materials. Cover every facet the question implies; separate distinct items rather than blending them. Do not introduce specifics absent from the materials. Be specific where the materials are specific. No preamble.'].join('\n');
  },

  multiStepKickoffUserPrompt(_input: MultiStepKickoffInput): string {
    return 'Begin. Plan to issue at least 2 distinct retrieval queries (varying angle/entity/wording) before finalizing. Output your first action JSON now.';
  },

  retrievalInjectionUserPrompt(input: RetrievalInjectionInput): string {
    return [`RETRIEVAL RESULTS (query: "${input.query}", ${input.resultCount} hits):`, input.results, '', 'Before your next action, check: (1) what aspect of the question is still uncovered by these results? (2) would any specific in a final answer be unsupported? (3) have you issued >= 2 distinct queries yet? If any gap exists, issue another retrieve with a refined, non-redundant query. Otherwise finalize.', '', 'Next JSON action:'].join('\n');
  },
};
