#!/usr/bin/env node
/**
 * Build the Node.js sidecar for Tauri production.
 *
 * Bundles packages/server/src/local/service.ts into a single JS file
 * at app/src-tauri/resources/service.js using esbuild JS API.
 *
 * Usage:
 *   node scripts/build-sidecar.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const resourcesDir = path.join(root, 'app', 'src-tauri', 'resources');
const outFile = path.join(resourcesDir, 'service.js');
const entryPoint = path.join(root, 'packages', 'server', 'src', 'local', 'service.ts');

// Ensure resources directory exists
fs.mkdirSync(resourcesDir, { recursive: true });

console.log('[build-sidecar] Bundling server into', outFile);

// Native modules that can't be bundled — must be installed alongside the sidecar
const EXTERNAL = [
  'better-sqlite3',
  '@vscode/sqlite3',
  'bullmq',
  'ioredis',
  'pg',
  'postgres',
  'drizzle-orm',
  'drizzle-orm/*',
  'mammoth',
  'pdf-parse',
  'exceljs',
  'archiver',
  '@fastify/static',
  'playwright-core',
  'playwright-core/*',
  '@playwright/*',
  'chromium-bidi',
  'chromium-bidi/*',
];

try {
  // Dynamic import esbuild (available via vite dependency)
  const esbuild = await import('esbuild');

  const result = await esbuild.build({
    entryPoints: [entryPoint],
    bundle: true,
    platform: 'node',
    target: 'node20',
    format: 'esm',
    outfile: outFile,
    external: EXTERNAL,
    sourcemap: true,
    minify: true,
    banner: {
      js: '// Waggle Sidecar — bundled server for Tauri desktop\n'
        + '// Generated by scripts/build-sidecar.mjs\n'
        + 'import { createRequire } from "node:module";\n'
        + 'const require = createRequire(import.meta.url);\n',
    },
    logLevel: 'warning',
  });

  if (result.errors.length > 0) {
    console.error('[build-sidecar] Build errors:', result.errors);
    process.exit(1);
  }

  if (result.warnings.length > 0) {
    console.warn(`[build-sidecar] ${result.warnings.length} warnings (non-blocking)`);
  }

  const stat = fs.statSync(outFile);
  const sizeMB = (stat.size / 1024 / 1024).toFixed(1);
  console.log(`[build-sidecar] Done. Output: ${sizeMB} MB`);

  // Copy marketplace seed database if it exists
  const marketplaceDb = path.join(root, 'packages', 'marketplace', 'seed', 'marketplace.db');
  if (fs.existsSync(marketplaceDb)) {
    fs.copyFileSync(marketplaceDb, path.join(resourcesDir, 'marketplace.db'));
    console.log('[build-sidecar] Copied marketplace.db seed');
  }
} catch (err) {
  console.error('[build-sidecar] Build failed:', err.message);
  process.exit(1);
}
